[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  GO_VERSION = "1.20"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"